### PR TITLE
chore: add domain for `FlexColorScheme` documentation site

### PR DESCRIPTION
**Pull request by rydmike**
This documentation site is for the open source Flutter FlexColorScheme package https://pub.dev/packages/flex_color_scheme, having its code repo on GitHub here https://github.com/rydmike/flex_color_scheme.

I decided to keep the documentation in a separate repo for increased documentation change flexibility, and to not burden the code repo with documentation images and animated GIFs. The documentation content is still work in progress. I expect to complete it during next week and then publish the stable version of FlexColorScheme v5.0.0 that the documentation site is intended for.

**Question**: I might not use the www CNAME for this site for anything, **if so,** is it OK if I point it to the doc site and add it as another domain too?

### CODE REVIEW

**Comment by rydmike** [comment]
Thanks @Salakar, not 100% sure if I will use the www elsewhere yet, let's start with the "docs" CNAME I added for now. 

GoDaddy where the ns server config is now seems to offer enough config and setup options that I need for now at least, even if they hide them well. 

I plan to later setup cnames for the examples and tutorials so they get domains like:

playground.flexcolorscheme.com
allthemes.flexcolorscheme.com
fourthemes.flexcolorscheme.com
customtheme.flexcolorscheme.com
basictheme.flexcolorscheme.com

in addition to: 

docs.flexcolorscheme.com pointed here.

Maybe I will find some use for www.flexcolorscheme.com, I might update my blog info about it and point it there too.

For examples/tutorial builds, I think I might host the builds later on Firebase. Currently they are on on my github pages and I don't think it allows me to setup multiple domains and subdomains. I have rydmike.com domain pointed to it now where the are now and a simple test/build/deploy GitHub actions that publishes the samples when I release new version of the package. Works well enough. If I move them to Firebase I first need to figure out how to do that with Firebase, but there seems to be plenty of examples around.

----

BTW, I got the tip earlier from Chris Sells while he was still at Google, about your nice and handy docs.page. Really liking it so far, simple, sure not a lot of features, but imo enough for most docs. Might have found some minor issues, but need to verify with separate tests. If they were issues, I'll post them separately of course.

**Comment by Salakar** [comment]
> BTW, I got the tip earlier from Chris Sells while he was still at Google, about your nice and handy docs.page. Really liking it so far, simple, sure not a lot of features, but imo enough for most docs. Might have found some minor issues, but need to verify with separate tests. If they were issues, I'll post them separately of course.

Oh cool, that's great to hear, please post any bugs or feature requests you have as issues, we're constantly improving docs.page so this will be helpful!

**Comment by Salakar** [comment]
If everything is in order on DNS then the domain should spring to life in a few minutes - just takes a couple minutes to register domain on the infra and auto-provision ssl certs

**Comment by rydmike** [comment]
Works great - thx! 💙

**Pull request merged**
