### PR TITLE
feat: QOL updates

### PR DESCRIPTION
**Pull request by Ehesp**
- [x] convert layout to CSS Grid for easier control & maximum space usage
- [x] update dark mode colors to gray tone vs blue
- [x] remove heading borders
- [x] remove layout options
- [x] convert to Highlight.js from Prism
  - [x] fix "copy" button
  - [x] remove Prism dependencies
  - [x] add code titles back in (manually)
- [x] rework mobile sidebar navigation
- [x] rework table styling (disable TW Prose on tables?)
- [x] support custom favicon url (fallback to logo)
- [x] `Tabs` are broken. Single Tab items are nested within a `p` tag: https://github.com/mdx-js/mdx/issues/1529 https://github.com/mdx-js/mdx/issues/1451
- [x] Support "System" theme + Dark/Light 
- [x] Support `.mdx` files only 

### CHANGES:

- Broken HTML / unclosed tags will no longer render - a 500 error page will be thrown
- Invalid components will now not be rendered, rather than 500 error
- Sync'd tabs are handled on the client now. Removed loads of complex logic, can revisit if it is an issue.

### CODE REVIEW

**Comment by Salakar** [comment]
Some issues when resizing width (content seems right fixed and moves left when you reduce width); 
image

**Comment by Ehesp** [comment]
Yeah trying to figure out the best way to maximize the width. Have an idea in mind just need to think how to actually do it :D

**Comment by Salakar** [comment]
#### 📝Changed routes:


| [**/_debug/\[...slug\]**](https://oss-docs-kooodbt1z-invertase.vercel.app/_debug/[...slug]) | [**/**](https://oss-docs-kooodbt1z-invertase.vercel.app/) |
|:-:|:-:|
|<a href="https://oss-docs-kooodbt1z-invertase.vercel.app/_debug/[...slug]">Screenshot of /_debug/[...slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/KG-n5xxEXQrDNsY9ng89LIZ-L3th0RrXyOXivDdnjtlZblNdXpmZrcQIBWPChPOQW1S4tkR5pX3JxfKeEjAeFw.png">(view full size)</a> |<a href="https://oss-docs-kooodbt1z-invertase.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/uD_OAAYVinE4xrATrkFd65KN15MeyvzJSHJadyI9Yedx-gjPzK4N_v0EJ6EQbGnFtp0dsW15CPho4L-kJKlKgg.png">(view full size)</a> |







Commit 0bd3ce6efaf99b49f25fa3a4575202dc5daa0f31 (https://oss-docs-kooodbt1z-invertase.vercel.app).

**Comment by Salakar** [comment]
Notes for another day / PR;

 - debug page incomplete
 - tab components incomplete (commented out in sections)
 - RenderError.tsx incomplete and not used anywhere
 - RepoInfo.tsx incomplete and not used anywhere
 - ErrorBoundary.tsx incomplete

**Pull request merged**
