### PR TITLE
Update domains.json

### PR DESCRIPTION
**Pull request by fikretsengul**

### CODE REVIEW

**Comment by Ehesp** [comment]
@fikretsengul Just going to hold off merging this for now, currently doing some updates to custom domains

**Comment by Ehesp** [comment]
@fikretsengul Hey, I'm going to close this PR as we're moving away from using the domains.json file to define custom domains. They are now handled internally and we're going to work on an improved and more sustainable solution going forwards.

I've added your domain to the internal list, so once you add the CNAME record (after propagation) you'll be able to access your docs there.

**Comment by Ehesp** [comment]
https://fab.fikretsengul.com/ is working 👍

**Comment by fikretsengul** [comment]
@Ehesp Hello again, first of all I wish you a happy new year. I hope everything is going well. I see that the new domain configuration feature is not yet complete, so could you please change the address of my documentation?

Old one: ["fab.fikretsengul.com", "fikretsengul/fab"]
New one: ["docs.flutterboilerplate.dev", "fikretsengul/docs"]

**Comment by fikretsengul** [comment]
@Ehesp Hey again, any news?

**Pull request closed without merging**
