### PR TITLE
feat: debug page

### PR DESCRIPTION
**Pull request by cabljac**
- add debug SSG page at _debug/[[...slug]]
- add handling for undefined mdx components (that are neither exported nor our presets)
- adapted existing layouts and context to be used in debug page, can navigate through different debug pages on left

TODO:
- cover everything with tests
- type the custom remark plugins properly
- handle other errors ( unclosed tags for example don't seem to be thrown explicitly by mdx-bundler, may need custom handler)
- layout and design of debug page

---

Example: `/_debug/cabljac/test-docs/test`

### CODE REVIEW

**Comment by Salakar** [comment]
#### 📝Changed routes:


| [**…er\]/\[name\]/\[\[...slug\]\]**](https://docs-page-kbs2t95v9-invertase.vercel.app/[owner]/[name]/[[...slug]]) | [**/_debug/\[\[...slug\]\]**](https://docs-page-kbs2t95v9-invertase.vercel.app/_debug/[[...slug]]) |
|:-:|:-:|
|<a href="https://docs-page-kbs2t95v9-invertase.vercel.app/[owner]/[name]/[[...slug]]">Screenshot of /[owner]/[name]/[[...slug]]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/LelKHGKC2YH_MIyuU4n6aquB-vK8KENnmU-uMQQS8KKmoycf8_M6txx5HR9-STH2jAYFshZsMStDKcgee0Mlfw.png">(view full size)</a> |<a href="https://docs-page-kbs2t95v9-invertase.vercel.app/_debug/[[...slug]]">Screenshot of /_debug/[[...slug]]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_AhQgFHZU6gOgU-r67z2xXzJgIhC5qUnE3E2hT9Ol59HX_2EsnbVcHEj27AOy3mXvs3ukbJvhxynWowEKQvf4w.png">(view full size)</a> |







Commit 7666dc7e30cf6e34b0fa12f948992d1e29aaf54b (https://docs-page-kbs2t95v9-invertase.vercel.app).

**Comment by Salakar** [comment]
What's your thoughts on the `Found` column being something like green/red check marks since (as far as I can tell) it'd always either be the same data or no data displayed there otherwise compared to `Looked for`

**Comment by cabljac** [comment]
> What's your thoughts on the `Found` column being something like green/red check marks since (as far as I can tell) it'd always either be the same data or no data displayed there otherwise compared to `Looked for`
> 
> image
> 
> Is it possible to also make the sub header look different to the other rows / look like headers here:
> 
> image

100% this makes sense

**Comment by Salakar** [comment]
#### 📝 Changed routes:


| [**…er\]/\[name\]/\[\[...slug\]\]**](https://docs-page-qslnlzzl7-invertase.vercel.app/[owner]/[name]/[[...slug]]) | [**/_debug/\[\[...slug\]\]**](https://docs-page-qslnlzzl7-invertase.vercel.app/_debug/[[...slug]]) |
|:-:|:-:|
|<a href="https://docs-page-qslnlzzl7-invertase.vercel.app/[owner]/[name]/[[...slug]]">Screenshot of /[owner]/[name]/[[...slug]]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Fcn_H1QUDvY9clpIC7jpRTGljo1RmfoiWvacEpOHyXOBP7wMq1lIY7vRGMssm-91OnM0F82AIz8tgrt7owEX3g.png">(view full size)</a> |<a href="https://docs-page-qslnlzzl7-invertase.vercel.app/_debug/[[...slug]]">Screenshot of /_debug/[[...slug]]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/kkYswvikFapgvluxpVoac_kl1WBJ0WMC6gGGMO2wE6nIfRtjX-pOtPjkInkKOo_S2vij5SdGiNpMoSz7lqvjxQ.png">(view full size)</a> |







Commit 09638cd4f06102b1f609fc430d3d0dae2bec446e (https://docs-page-qslnlzzl7-invertase.vercel.app).

**Pull request closed without merging**
